language: java
jdk:
  - openjdk8

script:
  - mvn test
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - chubyrd1@gmail.com
      - bernardomassone@hotmail.com
      - andonifzabala@gmail.com
      - juanwbenitez@gmail.com
    on_failure: always